= バイナリビルド
:navtitle: バイナリビルド

include::vars.adoc[]

[#moving_on_from_s2i]
== S2Iからのステップアップ
以前に見たように、S2Iはソースコードからコンテナを生成する素晴らしい方法ですが、日々の高速な反復開発（iterative development）にはプロセスが少し遅すぎます。
例えば、CSSを変更したり、クラス内の1つのメソッドを変更したりする場合、完全なgitコミットとビルドサイクルを経たくはありません。
このラボでは、迅速な反復（iteration）のための、より効率的な方法を紹介します。
その際、コードをデバッグする方法も紹介します。
MLB Parksサービスをビルドしたので、次に進んでいくつかの素早い変更を加えてみましょう。

[#fast_iterative_code_change_using_binary_deploy]
== バイナリデプロイを使用した高速な反復的コード変更

OpenShiftのコマンドラインには、ローカルマシンからデプロイメントを実行する機能があります。
このケースではS2Iを使用しますが、ローカルマシンからwarファイルを受け取り、それをイメージに組み込む（bake）ようOpenShiftに指示します。
この開発パターンを行うことで、ローカルマシンでの迅速なビルド（ローカルキャッシュとマシンの全能力の恩恵を受ける）が可能になり、その後warファイルを素早く送信するだけで済みます。
NOTE: このパターンを使用して、作業ディレクトリをS2Iビルダーに送信し、OpenShift上でMavenビルドを実行させることもできます。
ローカルディレクトリを使用すると、ローカルマシンにMavenやJavaツールチェーンがなくてもよくなり、プッシュを伴うgitコミットも不要になります。
詳細は
// {openshift-docs-url}/builds/basic-build-operations.html#builds-basic-start-source_basic-build-operations[公式ドキュメント] を参照してください。


[#using_binary_deployment]
== 演習: バイナリデプロイメントの使用

[#clone_source]
=== ソースのクローン
最初のステップは、GitHubからワークショップ環境にMLBのソースコードをクローンすることです：

[.console-input]
[source,bash]
----
git clone https://github.com/openshift-roadshow/mlbparks.git
----

NOTE: このガイドではスクリーンショットのためにIntellijを使用していますが、これはツールチェーンに関係なく機能するはずです。
JBoss Developer StudioとJBoss Developer Toolsには、IDEから直接これをシームレスに実行できる機能が組み込まれています。

[#setup_the_build_of_the_war_file]
=== WARファイルのビルド設定
マシンにMavenがすべてセットアップされている場合は、`mlbparks` ディレクトリに `cd` して `mvn package` を実行できます。

[#docker_for_maven]
[TIP]
====
マシンにMavenがなくてもdockerを実行できる場合は、代わりにリポジトリディレクトリをマウントし、コンテナ内からビルドコマンドを実行できます。
. 上記で `git clone` を実行したディレクトリ内から、次のコマンドを実行します：
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
docker run -it --rm --user 0 --name maven_builder -v ~/.kube:/home/jboss/.kube -v $(pwd):/workspaces -w /workspaces registry.access.redhat.com/ubi8/openjdk-11 /bin/bash
----
+
.
次に、（コンテナ内で）このコマンドを実行して、コンテナに最新バージョンの `oc` をローカルインストールします：
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
mkdir -p $HOME/bin && curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz |
\
    tar -xvzf - -C $HOME/bin/ oc && chmod 755 $HOME/bin/oc && ln -s $HOME/bin/oc $HOME/bin/kubectl
----
+
.
最後に、ビルダーコンテナ内からOpenShiftクラスターにまだ接続していることを、以下を実行して出力を比較することで確認します：
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc whoami --show-server
----
+
[.console-output]
[source,bash,subs="+macros,+attributes"]
----
https://{ocp4_starter_apps_domain}:30713
----

完了したら、以下で概説されているコマンドに従うことができるはずです。
====

[.console-input]
[source,bash,subs="+attributes,macros+"]
----
cd mlbparks
mvn package
----

ROOT.warの出力場所（directory）に注意してください。後でそのディレクトリが必要になります。

[#code_change]
=== コード変更

ソースコード変更の時間です！

以下のパスにある `BackendController` Javaクラスを編集します：

[.console-output]
[source,bash]
----
src/main/java/com/openshift/evg/roadshow/rest/BackendController.java
----

これはサービスの基本情報を返すRESTエンドポイントで、以下のアドレスでアクセスできます：

[source,bash,role="copypaste",subs="+attributes"]
----
http://mlbparks-{ocp4_starter_project}.{ocp4_starter_apps_domain}/ws/info/
----

23行目を変更し、"MLB Parks" の前に _AMAZING_ を加えて、以下のようにしてください：

[source,java]
----
return new Backend("mlbparks", "AMAZING MLB Parks", new Coordinates("39.82", "-98.57"), 5);
----

ファイルを保存し、ソースフォルダのルートから再度 `mvn package` を実行するのを忘れないでください：

[.console-input]
[source,bash,subs="+attributes,macros+"]
----
mvn package
----

[#doing_the_binary_build]
=== バイナリビルドの実行

さて、warファイルがビルドできたので、それを使ってビルドを開始しましょう。
Mavenでwarファイルをビルドした場合：

[.console-input]
[source,bash,subs="+attributes,macros+"]
----
oc start-build bc/mlbparks --from-file=target/ROOT.war --follow
----

NOTE: ターミナルでビルドの出力を追いたい場合、--followはオプションです。
ラベルとRecreateデプロイメントストラテジーを使用しているため、新しいデプロイメントが完了するとすぐにマップ名が更新されます。
Recreateデプロイメントストラテジーでは、新しいデプロイメントを行う前にまずPodを破棄（tear down）します。
Podが破棄されると、parksmapサービスはレイヤーからMLBParksマップを削除します。
それが（訳注：新しいPodが）立ち上がると、レイヤーは自動的に新しいタイトルで追加されます。
これはRollingデプロイメントでは起こりませんでした。なぜなら、Rollingは古いPodを停止（take down）する前に新しいバージョンのPodをスピンアップするからです。
Rollingストラテジーはゼロダウンタイムデプロイメントを可能にします。

Topologyビューから進行中のデプロイメントを追うことができます。完了すると、以下のURLで新しいコンテンツが表示されます：

[source,bash,role="copypaste",subs="+attributes"]
----
http://mlbparks-{ocp4_starter_project}.{ocp4_starter_apps_domain}/ws/info/
----

これで、ビルドとデプロイのプロセスをスピードアップする方法がわかりました。